port: 4000
base_author: "the Organisers"
permalink: /news/:title/

# Navigation
navigationLinks:
 - {permalink: '/about/', text: "About"}
 - {permalink: '/news/', text: "News"}
 - {permalink: '/speak/', text: "Speak"}
 - {permalink: '/assistance/', text: "Assistance"}
 - {permalink: '/attend/', text: "Attend"}
 - {permalink: '/sponsor/', text: "Sponsor"}
 - {permalink: '/conduct/', text: "Conduct"}


include: 
 - _pages

exclude:
 - README.md
 - CNAME
 - Gemfile
 - Gemfile.lock
 - new_post
 - prospectus.pdf

future: true

collections:
    talks:  
        output: true
        permalink: /:collection/:name/
