port: 4000
header-img: "img/headers/DarlingHarbour_header.jpg"

permalink: /news/:title/

# Navigation
navigationLinks:
 - {permalink: '/about/', text: "About"}
 - {permalink: '/news/', text: "News"}
 - {permalink: '/speak/', text: "Speak"}
 - {permalink: '/schedule/', text: "Schedule"}
 - {permalink: '/attend/', text: "Attend"}
 - {permalink: '/sponsor/', text: "Sponsor"}
 - {permalink: '/conduct/', text: "Conduct"}
